//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.14 at 02:01:55 PM EDT 
//


package com.derbis.model;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Field complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Field"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;attribute name="seq" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="name" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="bitLength" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *       &lt;attribute name="characterSet" use="required" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="compaction" type="{urn:epcglobal:tdt:xsd:1}CompactionMethodList" /&gt;
 *       &lt;attribute name="compression" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="padChar" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="padDir" type="{urn:epcglobal:tdt:xsd:1}PadDirectionList" /&gt;
 *       &lt;attribute name="bitPadDir" type="{urn:epcglobal:tdt:xsd:1}PadDirectionList" /&gt;
 *       &lt;attribute name="decimalMinimum" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="decimalMaximum" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="length" type="{http://www.w3.org/2001/XMLSchema}integer" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Field", namespace = "urn:epcglobal:tdt:xsd:1")
public class Field {

    @XmlAttribute(name = "seq", required = true)
    protected BigInteger seq;
    @XmlAttribute(name = "name", required = true)
    protected String name;
    @XmlAttribute(name = "bitLength")
    protected BigInteger bitLength;
    @XmlAttribute(name = "characterSet", required = true)
    protected String characterSet;
    @XmlAttribute(name = "compaction")
    protected String compaction;
    @XmlAttribute(name = "compression")
    protected String compression;
    @XmlAttribute(name = "padChar")
    protected String padChar;
    @XmlAttribute(name = "padDir")
    protected PadDirectionList padDir;
    @XmlAttribute(name = "bitPadDir")
    protected PadDirectionList bitPadDir;
    @XmlAttribute(name = "decimalMinimum")
    protected String decimalMinimum;
    @XmlAttribute(name = "decimalMaximum")
    protected String decimalMaximum;
    @XmlAttribute(name = "length")
    protected BigInteger length;

    /**
     * Gets the value of the seq property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getSeq() {
        return seq;
    }

    /**
     * Sets the value of the seq property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setSeq(BigInteger value) {
        this.seq = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the bitLength property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBitLength() {
        return bitLength;
    }

    /**
     * Sets the value of the bitLength property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBitLength(BigInteger value) {
        this.bitLength = value;
    }

    /**
     * Gets the value of the characterSet property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCharacterSet() {
        return characterSet;
    }

    /**
     * Sets the value of the characterSet property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCharacterSet(String value) {
        this.characterSet = value;
    }

    /**
     * Gets the value of the compaction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompaction() {
        return compaction;
    }

    /**
     * Sets the value of the compaction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompaction(String value) {
        this.compaction = value;
    }

    /**
     * Gets the value of the compression property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompression() {
        return compression;
    }

    /**
     * Sets the value of the compression property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompression(String value) {
        this.compression = value;
    }

    /**
     * Gets the value of the padChar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPadChar() {
        return padChar;
    }

    /**
     * Sets the value of the padChar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPadChar(String value) {
        this.padChar = value;
    }

    /**
     * Gets the value of the padDir property.
     * 
     * @return
     *     possible object is
     *     {@link PadDirectionList }
     *     
     */
    public PadDirectionList getPadDir() {
        return padDir;
    }

    /**
     * Sets the value of the padDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link PadDirectionList }
     *     
     */
    public void setPadDir(PadDirectionList value) {
        this.padDir = value;
    }

    /**
     * Gets the value of the bitPadDir property.
     * 
     * @return
     *     possible object is
     *     {@link PadDirectionList }
     *     
     */
    public PadDirectionList getBitPadDir() {
        return bitPadDir;
    }

    /**
     * Sets the value of the bitPadDir property.
     * 
     * @param value
     *     allowed object is
     *     {@link PadDirectionList }
     *     
     */
    public void setBitPadDir(PadDirectionList value) {
        this.bitPadDir = value;
    }

    /**
     * Gets the value of the decimalMinimum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalMinimum() {
        return decimalMinimum;
    }

    /**
     * Sets the value of the decimalMinimum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalMinimum(String value) {
        this.decimalMinimum = value;
    }

    /**
     * Gets the value of the decimalMaximum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDecimalMaximum() {
        return decimalMaximum;
    }

    /**
     * Sets the value of the decimalMaximum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDecimalMaximum(String value) {
        this.decimalMaximum = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLength(BigInteger value) {
        this.length = value;
    }

}
